import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { NawcPlugin } from "@nawc/plugin";

const header = "<!-- Generated by NAWC. Changes will be replaced. -->\n\n";

export async function syncSkills(
  projectDir: string,
  plugins: readonly NawcPlugin[],
): Promise<string> {
  const skillsDir = path.join(projectDir, ".skills");
  for (const plugin of plugins) {
    for (const skill of plugin.skills ?? []) {
      const directory = path.join(skillsDir, skill.name);
      const file = path.join(directory, "SKILL.md");
      await mkdir(directory, { recursive: true });
      try {
        const existing = await readFile(file, "utf8");
        if (!existing.startsWith(header))
          throw new Error(`Refusing to overwrite user-owned skill: ${file}`);
      } catch (error) {
        if (error instanceof Error && !error.message.includes("ENOENT")) throw error;
      }
      await writeFile(file, header + skill.content.trim() + "\n", "utf8");
    }
  }
  return skillsDir;
}
