import { mkdir, readFile, readdir, rm, rmdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { NawcPlugin } from "@nawc/plugin";

const legacyHeader = "<!-- Generated by NAWC. Changes will be replaced. -->\n\n";
const generatedHeader = "---\n# Generated by NAWC. Changes will be replaced.\n";

function isGeneratedSkill(content: string): boolean {
  return content.startsWith(legacyHeader) || content.startsWith(generatedHeader);
}

function renderGeneratedSkill(content: string): string {
  const trimmed = content.trim();
  if (trimmed.startsWith("---")) {
    return `${generatedHeader}${trimmed.slice(3).replace(/^\n/, "")}\n`;
  }
  return `${legacyHeader}${trimmed}\n`;
}

export async function syncSkills(
  projectDir: string,
  plugins: readonly NawcPlugin[],
): Promise<string> {
  const skillsDir = path.join(projectDir, ".skills");
  const generatedSkills = new Set<string>();
  for (const plugin of plugins) {
    for (const skill of plugin.skills ?? []) {
      generatedSkills.add(skill.name);
      const directory = path.join(skillsDir, skill.name);
      const file = path.join(directory, "SKILL.md");
      await mkdir(directory, { recursive: true });
      try {
        const existing = await readFile(file, "utf8");
        if (!isGeneratedSkill(existing))
          throw new Error(`Refusing to overwrite user-owned skill: ${file}`);
      } catch (error) {
        if (error instanceof Error && !error.message.includes("ENOENT")) throw error;
      }
      await writeFile(file, renderGeneratedSkill(skill.content), "utf8");
    }
  }
  for (const entry of await readdir(skillsDir, { withFileTypes: true })) {
    if (!entry.isDirectory() || generatedSkills.has(entry.name)) continue;
    const file = path.join(skillsDir, entry.name, "SKILL.md");
    try {
      const existing = await readFile(file, "utf8");
      if (!isGeneratedSkill(existing)) continue;
      await rm(file);
      await rmdir(path.join(skillsDir, entry.name));
    } catch (error) {
      const code =
        error && typeof error === "object" && "code" in error && typeof error.code === "string"
          ? error.code
          : undefined;
      if (code !== "ENOENT" && code !== "ENOTEMPTY") throw error;
    }
  }
  return skillsDir;
}
