import { definePlugin } from "@nawc/plugin";

const markdown = (lines: readonly string[]) =>
  lines.join("\n").replaceAll("[[tick]]", String.fromCharCode(96));

const nawcSkill = markdown([
  "---",
  "name: nawc",
  "description: Use when reading, writing, or relying on NAWC notes.",
  "---",
  "",
  "# nawc",
  "",
  "NAWC notes are HTML files used as the durable workspace beside the codebase.",
  "",
  "Use NAWC notes to store tickets, design decisions, probes, receipts, links, and splash zones.",
  "",
  "## Core elements",
  "",
  "Use these elements directly in note HTML.",
  "",
  "[[tick]][[tick]][[tick]]html",
  "<interactive>...</interactive>",
  "or",
  '<interactive file="path/to/file.html" />',
  "[[tick]][[tick]][[tick]]",
  "",
  "A self-contained inline or file-backed HTML prototype. It runs in a sandboxed iframe. Inline scripts and styles are allowed.",
  "",
  "[[tick]][[tick]][[tick]]html",
  '<ref file="path/to/file" />',
  "[[tick]][[tick]][[tick]]",
  "",
  "Shows live source from the codebase.",
  "",
  "[[tick]][[tick]][[tick]]html",
  '<runnable file="path/to/file" />',
  "[[tick]][[tick]][[tick]]",
  "",
  "Shows live source and lets the reader run it when supported.",
  "",
  "## Syntax skills",
  "",
  "NAWC config emits syntax-specific skills.",
  "",
  "Before adding selector or runner attributes to [[tick]]<ref>[[tick]] or [[tick]]<runnable>[[tick]], load the emitted syntax skill for that language or test framework.",
  "",
  "A syntax skill defines:",
  "",
  "- valid [[tick]]syntax[[tick]] values",
  "- valid selector attributes",
  "- valid runnable attributes",
  "- supported declaration kinds",
  "- supported test or example kinds",
  "",
  "Do not invent syntax-specific attributes.",
  "",
  "## Notebook source files",
  "",
  "NAWC notes may use source files stored beside the notes in the notebook [[tick]]src[[tick]] directory.",
  "",
  "Use notebook source files when [[tick]]<ref>[[tick]] or [[tick]]<runnable>[[tick]] needs live source that does not belong in the product codebase.",
  "",
  "Good uses include:",
  "",
  "- prototypes",
  "- runnable examples",
  "- focused tests",
  "- fixtures",
  "- mock data",
  "- small reference implementations",
  "",
  "## Rules",
  "",
  "- Reference live code with [[tick]]<ref>[[tick]] or [[tick]]<runnable>[[tick]]. Do not paste source code into those elements.",
  "- Use [[tick]]<interactive>[[tick]] for UI, flow, layout, animation, or visual preference refinement.",
  "- Use [[tick]]<runnable>[[tick]] for behavior, data shape, API shape, state, validation, and error examples.",
  "- Use [[tick]]<ref>[[tick]] when the ticket should follow an existing implementation pattern.",
  "- Link notes to represent parent, child, dependency, blocking, related, superseding, and affected relationships.",
  "- Put details in the note that owns them.",
  "- When one note contains multiple implementation goals, use [[tick]]split[[tick]].",
  "- Keep notebook source files small and focused.",
  "- Name notebook source files after the ticket, design decision, or probe they support.",
  "- Reference notebook source files with [[tick]]<ref>[[tick]] or [[tick]]<runnable>[[tick]].",
  "- Do not treat notebook source files as production code unless the user explicitly promotes them.",
  "- If a notebook source file becomes production-relevant, create an implementation ticket for moving or adapting it.",
]);

const orientSkill = markdown([
  "---",
  "name: orient",
  "description: Use before refining, splitting, implementing, or reviewing a NAWC ticket.",
  "---",
  "",
  "# orient",
  "",
  "Recover context from NAWC before asking the user or changing a ticket.",
  "",
  "## Process",
  "",
  "1. Read the current request or ticket note.",
  "2. Follow linked parent, child, dependency, blocking, related, superseding, and affected notes.",
  "3. Read relevant design decisions.",
  "4. Inspect relevant receipts: probes, tests, runnables, interactives, refs, and linked notes.",
  "5. List blocking questions.",
  "6. List dependencies.",
  "7. List current splash zone items.",
  "",
  "## Output",
  "",
  "[[tick]][[tick]][[tick]]md",
  "## Orientation",
  "",
  "Current ticket:",
  "- ...",
  "",
  "Linked tickets:",
  "- parent:",
  "- children:",
  "- depends on:",
  "- blocks:",
  "- related to:",
  "- supersedes:",
  "- affects:",
  "",
  "Design decisions:",
  "- ...",
  "",
  "Receipts:",
  "- ...",
  "",
  "Blocking questions:",
  "- ...",
  "",
  "Dependencies:",
  "- ...",
  "",
  "Splash zone:",
  "- ...",
  "[[tick]][[tick]][[tick]]",
  "",
  "## Rules",
  "",
  "* Do not ask the user a question already answered by a NAWC note.",
  "* Follow linked notes before broad search.",
  "* Treat tests and runnable examples as stronger evidence than prose.",
  "* If prose conflicts with a probe, report the conflict.",
  "* Keep the output brief.",
]);

const refineSkill = markdown([
  "---",
  "name: refine",
  "description: Use when a request or ticket is not ready for implementation.",
  "---",
  "",
  "# refine",
  "",
  "Turn a vague request or ticket into ready tickets through user decisions, probes, and splits.",
  "",
  "The user makes design decisions. The agent asks, suggests, records, probes, and splits.",
  "",
  "## Process",
  "",
  "1. Run [[tick]]orient[[tick]].",
  "2. Restate the current ticket in one or two sentences.",
  "3. Identify the next blocking question.",
  "4. Ask the user exactly one question.",
  "5. Record the user’s answer as a design decision.",
  "6. Run [[tick]]probe[[tick]] unless the decision is administrative only.",
  "7. Run the split check.",
  "8. If the ticket fails the split check, run [[tick]]split[[tick]].",
  "9. If [[tick]]split[[tick]] creates child tickets, ask the user to select exactly one child ticket to refine next.",
  "10. Continue refining only the selected child ticket.",
  "11. Stop when [[tick]]ticket-ready[[tick]] passes.",
  "",
  "## Administrative decisions",
  "",
  "A decision is administrative only when it affects only:",
  "",
  "- ticket name",
  "- ticket priority",
  "- ticket owner",
  "- note location",
  "- rough scheduling",
  "- link organization",
  "",
  "Administrative decisions do not require probes.",
  "",
  "## Split check",
  "",
  "A ticket must be split if any item is true:",
  "",
  "- it has more than one implementation goal",
  "- it has more than one primary test seam",
  "- it includes work for multiple apps or services",
  "- it includes multiple unrelated API endpoints",
  "- it includes multiple unrelated data models",
  "- it includes multiple independent user-facing behaviors",
  "- it contains implementation work that requires separate review",
  "- an agent would need to stop during implementation and create a new plan",
  "",
  "Specific detail does not make a ticket ready. Atomic scope makes a ticket ready.",
  "",
  "## Question rules",
  "",
  "- Ask one question at a time.",
  "- Ask the question that blocks implementation soonest.",
  "- Offer options when useful.",
  "- Do not decide for the user.",
  "- Do not create a complete architecture without user approval.",
  "- Do not refine multiple child tickets at once.",
  "- If the selected child ticket is blocked by a dependency, ask the user before switching to that dependency.",
]);

const splitSkill = markdown([
  "---",
  "name: split",
  "description: Use when a ticket cannot be implemented by one agent in one implementation session.",
  "---",
  "",
  "# split",
  "",
  "Turn one non-atomic ticket into child tickets connected in the ticket DAG.",
  "",
  "An implementation session is one uninterrupted implementation pass by an agent, without stopping to create a new plan.",
  "",
  "## Split triggers",
  "",
  "Split the ticket if any item is true:",
  "",
  "- more than one implementation goal",
  "- more than one primary test seam",
  "- work across multiple apps or services",
  "- multiple unrelated API endpoints",
  "- multiple unrelated data models",
  "- multiple independent user-facing behaviors",
  "- implementation work requiring separate review",
  "- implementation would require the agent to pause and re-plan",
  "",
  "## Process",
  "",
  "1. State which split triggers apply.",
  "2. Suggest child tickets.",
  "3. Ask the user to approve, remove, rename, or add child tickets.",
  "4. After approval, create or update child ticket notes.",
  "5. Move details from the parent ticket into the correct child tickets.",
  "6. Keep summary and coordination details in the parent ticket.",
  "7. Add links between parent and children.",
  "8. Add dependency links between child tickets.",
  "9. Ask the user to select exactly one child ticket to refine next.",
  "",
  "## Parent ticket",
  "",
  "A parent ticket must say whether it is:",
  "",
  "- an organizing ticket",
  "- a coordination ticket",
  "- an implementable ticket with child dependencies",
  "",
  "## Child ticket",
  "",
  "Each child ticket must include:",
  "",
  "- one implementation goal",
  "- parent link",
  "- known dependencies",
  "- inherited design decisions, if any",
  "- inherited receipts, if any",
  "- inherited splash zone items, if any",
  "",
  "## Rules",
  "",
  "- Do not split without user approval.",
  "- Split by behavior unless the user approves an architecture-based split.",
  "- Do not duplicate implementation details across child tickets.",
  "- Move details to the child ticket that owns them.",
  "- Preserve important history by marking it superseded instead of deleting it.",
  "- After splitting, refine only the child ticket selected by the user.",
]);

const probeSkill = markdown([
  "---",
  "name: probe",
  "description: Use after every non-administrative design decision.",
  "---",
  "",
  "# probe",
  "",
  "Represent a design decision with a deterministic artifact.",
  "",
  "A probe is attached to a design decision so future agents do not rely on prose alone.",
  "",
  "## Probe order",
  "",
  "Use the strongest available probe:",
  "",
  "1. test",
  "2. runnable example",
  "3. interactive prototype",
  "4. live ref",
  "",
  "## Required probes",
  "",
  "A probe is required when the decision affects:",
  "",
  "- behavior",
  "- API shape",
  "- data shape",
  "- UI",
  "- workflow",
  "- state",
  "- validation",
  "- error handling",
  "- persistence",
  "- integration",
  "- performance expectations",
  "- security behavior",
  "- accessibility behavior",
  "",
  "A probe is not required for administrative decisions only.",
  "",
  "## Probe types",
  "",
  "Use a test when the decision can be asserted.",
  "",
  "Use a runnable example for:",
  "",
  "- API shape",
  "- input/output examples",
  "- data transformations",
  "- state transitions",
  "- validation behavior",
  "- error behavior",
  "",
  "Use an interactive prototype for:",
  "",
  "- UI",
  "- visual preference",
  "- layout",
  "- flow",
  "- animation",
  "- interaction feel",
  "",
  "Use a live ref when the decision is to follow an existing code pattern.",
  "",
  "## Process",
  "",
  "1. Name the design decision.",
  "2. Choose the strongest available probe type.",
  "3. Create or update the probe.",
  "4. Ask the user to review the probe when it represents UI, API shape, behavior, or preference.",
  "5. Apply user feedback to the probe.",
  "6. Repeat until the user accepts it.",
  "7. Attach the probe to the ticket as a receipt.",
  "",
  "## If no probe can be created",
  "",
  "Write this under the design decision:",
  "",
  "[[tick]][[tick]][[tick]]md",
  "Probe: not available",
  "Reason: <specific reason>",
  "[[tick]][[tick]][[tick]]",
  "",
  "## Rules",
  "",
  "* One probe represents one design decision.",
  "* Prefer tests over all other probes.",
  "* Prefer runnable examples over prose for behavior.",
  "* Prefer interactive prototypes over prose for UI.",
  "* Do not keep decorative prototypes.",
  "* Keep historical probes only when they explain a superseded decision.",
]);

const ticketReadySkill = markdown([
  "---",
  "name: ticket-ready",
  "description: Use before implementing a ticket.",
  "---",
  "",
  "# ticket-ready",
  "",
  "Decide whether a ticket can be handed to an implementation agent.",
  "",
  "A ready ticket can be implemented by one agent in one implementation session.",
  "",
  "## Readiness checklist",
  "",
  "A ticket is ready only when all items are true:",
  "",
  "- it has one implementation goal",
  "- it can be implemented in one implementation session",
  "- it has one primary test seam",
  "- it has no blocking questions",
  "- user-approved design decisions are recorded",
  "- each non-administrative design decision has a probe or a written reason why no probe exists",
  "- dependencies are listed",
  "- splash zone is listed",
  "- done criteria are listed",
  "- required syntax skills are identified",
  "- relevant receipts are linked",
  "- implementation scope excludes sibling tickets",
  "",
  "## Output",
  "",
  "[[tick]][[tick]][[tick]]md",
  "## Ticket readiness",
  "",
  "Status: ready | not ready",
  "",
  "Failed checks:",
  "- ...",
  "",
  "Blocking questions:",
  "- ...",
  "",
  "Missing probes:",
  "- ...",
  "",
  "Dependencies:",
  "- ...",
  "",
  "Splash zone:",
  "- ...",
  "",
  "Done criteria:",
  "- ...",
  "",
  "Implementation handoff:",
  "- ...",
  "[[tick]][[tick]][[tick]]",
  "",
  "## Rules",
  "",
  "* Do not mark parent coordination tickets ready unless they contain direct implementation work.",
  "* Do not mark tickets ready with unresolved blocking questions.",
  "* Do not mark tickets ready without a splash zone.",
  "* Do not mark tickets ready if they contain multiple primary test seams.",
  "* If the ticket fails readiness, return to [[tick]]refine[[tick]] or [[tick]]split[[tick]].",
]);

const implementSkill = markdown([
  "---",
  "name: implement",
  "description: Use only when implementing a ready ticket.",
  "---",
  "",
  "# implement",
  "",
  "Implement one ready ticket using test-driven development.",
  "",
  "## Process",
  "",
  "1. Read the ticket.",
  "2. Confirm [[tick]]ticket-ready[[tick]] status.",
  "3. Read linked design decisions.",
  "4. Read linked probes and receipts.",
  "5. Read dependency tickets.",
  "6. Read splash zone before changing code.",
  "7. Identify the primary test seam.",
  "8. Write a failing test.",
  "9. Make the test pass.",
  "10. Refactor without changing behavior.",
  "11. Run relevant tests.",
  "12. Update or add receipts only when implementation changes evidence.",
  "13. Run [[tick]]review-implementation[[tick]].",
  "",
  "## Rules",
  "",
  "- Implement one ticket only.",
  "- Do not implement sibling tickets.",
  "- Do not change design decisions silently.",
  "- If implementation requires a design change, stop and ask the user.",
  "- If implementation reveals the ticket is not atomic, stop and run [[tick]]split[[tick]].",
  "- Test behavior, not private implementation details.",
  "- Do not add prose when a test or runnable example can represent the behavior.",
]);

const reviewImplementationSkill = markdown([
  "---",
  "name: review-implementation",
  "description: Use after implementing a ticket.",
  "---",
  "",
  "# review-implementation",
  "",
  "Review implementation against the ticket, design decisions, probes, receipts, and splash zone.",
  "",
  "## Process",
  "",
  "1. Read the implemented ticket.",
  "2. Inspect the code diff.",
  "3. Run relevant tests.",
  "4. Check each linked design decision.",
  "5. Check each probe.",
  "6. Check each receipt.",
  "7. Check each splash zone item.",
  "8. List required fixes.",
  "9. List optional follow-up tickets.",
  "10. Mark the ticket done only if required fixes are empty.",
  "",
  "## Review axes",
  "",
  "### Standards",
  "",
  "Check code quality.",
  "",
  "### Intent",
  "",
  "Check whether the implementation matches the ticket and design decisions.",
  "",
  "### Receipts",
  "",
  "Check whether probes, tests, runnables, interactives, refs, and prototypes still represent the implemented behavior.",
  "",
  "### Splash zone",
  "",
  "Check whether linked notes, tickets, decisions, receipts, or source files became stale.",
  "",
  "## Output",
  "",
  "[[tick]][[tick]][[tick]]md",
  "## Implementation review",
  "",
  "Standards:",
  "- pass | fail",
  "",
  "Intent:",
  "- pass | fail",
  "",
  "Receipts:",
  "- pass | fail",
  "",
  "Splash zone:",
  "- clean | stale | at risk",
  "",
  "Required fixes:",
  "- ...",
  "",
  "Optional follow-up tickets:",
  "- ...",
  "",
  "Done:",
  "- yes | no",
  "[[tick]][[tick]][[tick]]",
  "",
  "## Rules",
  "",
  "* Do not rewrite unrelated notes.",
  "* Fix stale receipts before adding explanatory prose.",
  "* If a splash zone item cannot be verified, mark it [[tick]]at risk[[tick]].",
  "* If implementation changed behavior, update the probe or design decision.",
  "* If implementation created new work, create a follow-up ticket.",
  "* A ticket is not done while required fixes remain.",
]);

export function nawcSkills() {
  return definePlugin({
    name: "nawcSkills",
    skills: [
      { name: "nawc", content: nawcSkill },
      { name: "orient", content: orientSkill },
      { name: "refine", content: refineSkill },
      { name: "split", content: splitSkill },
      { name: "probe", content: probeSkill },
      { name: "ticket-ready", content: ticketReadySkill },
      { name: "implement", content: implementSkill },
      { name: "review-implementation", content: reviewImplementationSkill },
    ],
  });
}
